#!/usr/bin/env bash
# Configures a brand new Ubuntu machine to the requirements asked in this task

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Add custom X-Served-By header
# shellcheck disable=SC2154
sudo sed -i "s/server_name _;/server_name _;\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/sites-available/default

sudo service nginx restart