#!/usr/bin/env bash
# Configures a brand new Ubuntu machine to the requirements asked in this task

apt-get update -y
apt-get install nginx -y

# Add custom X-Served-By header
# shellcheck disable=SC2154
sed -i "/listen 80 default_server;/a \\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

service nginx restart