#!/usr/bin/env bash
# Transfers a file from the client to a server

# Check if less than 4 parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Transfer the file to the server home directory using scp
scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
